move Step init logic to library
go-vela/worker pull request #239
Opened 2021-11-13 03:41 UTC by cognifloyd

Both the local and linux executors have to create a step object in a couple of places. This moves that logic into `library` (types) to facilitate reuse.

The executor can't use `StepFromContainer` because that relies on the container Environment which is not configured yet.  So, we rename `StepFromContainer` to `StepFromContainerEnvironment` to more accurately represent what it does. Then we add a new `StepFromBuildContainer` function to create a new Step and initialize it using data from a `library.Build` and a `pipeline.Container`.

For background, see the conversation here: https://github.com/go-vela/pkg-executor/pull/179#discussion_r735875710

This depends on https://github.com/go-vela/types/pull/205

- StepFromContainer -> StepFromContainerEnvironment
- Use library.StepFromBuildContainer to create new Steps

2021-11-13 03:43 UTC, cognifloyd commented
marking this as draft until https://github.com/go-vela/types/pull/205 is merged

2021-11-17 21:59 UTC, wass3r commented
i think we're good to open this up now

2021-11-18 00:20 UTC, cognifloyd commented
I'm not near a computer right now. The only thing left for this PR is to update the types module

2021-11-19 15:23 UTC, jbrockopp requested changes
Think we'll need to vendor in the latest changes from [go-vela/types](https://github.com/go-vela/types) for this to work properly:

`go get -u github.com/go-vela/types@master`

2021-11-19 17:05 UTC, cognifloyd commented
K. This is ready :)

2021-11-22 22:30 UTC, wass3r approved these changes

2021-11-23 16:32 UTC, jbrockopp approved these changes
LGTM

2021-11-23 16:33 UTC, merged