chore: Always make the built binary executable
go-vela/worker pull request #300
Opened 2022-04-05 22:30 UTC by cognifloyd

I keep forgetting to make the binary executable after I build with `make build-static` and before I build my new docker image.
This PR should save me from myself.

2022-04-14 06:23 UTC, cognifloyd commented
Rebased and removed `@` so that chmod shows in the output.

2022-04-15 14:00 UTC, kneal approved these changes
LGTM 🐬

2022-04-15 16:37 UTC, wass3r approved these changes

2022-04-15 20:06 UTC, jbrockopp requested changes
Could you help me understand why this change is necessary?

I ask because `go build`, by default, adds the executable (`+x`) permission to the binary:

```bash
$ make build; ls -al release/

### Building release/vela-worker binary
GOOS=linux CGO_ENABLED=0 \
		go build -a \
		-ldflags '-X github.com/go-vela/worker/version.Commit=98c0fc895260cf332dc8377a059f68932ead5a8a -X github.com/go-vela/worker/version.Date=2022-04-15T15:00:21Z -X github.com/go-vela/worker/version.Tag=v0.13.0' \
		-o release/vela-worker \
		github.com/go-vela/worker/cmd/vela-worker
total 109208
drwxr-xr-x   3 <user>  staff        96 Apr 15 15:00 .
drwxr-xr-x  27 <user>  staff       864 Apr 15 15:00 ..
-rwxr-xr-x   1 <user>  staff  55911466 Apr 15 15:00 vela-worker
```

```bash
$ make build-static; ls -al release/

### Building static release/vela-worker binary
GOOS=linux CGO_ENABLED=0 \
		go build -a \
		-ldflags '-s -w -extldflags "-static" -X github.com/go-vela/worker/version.Commit=98c0fc895260cf332dc8377a059f68932ead5a8a -X github.com/go-vela/worker/version.Date=2022-04-15T15:01:24Z -X github.com/go-vela/worker/version.Tag=v0.13.0' \
		-o release/vela-worker \
		github.com/go-vela/worker/cmd/vela-worker
total 76760
drwxr-xr-x   3 <user>  staff        96 Apr 15 15:01 .
drwxr-xr-x  27 <user>  staff       864 Apr 15 15:00 ..
-rwxr-xr-x   1 <user>  staff  39301120 Apr 15 15:01 vela-worker
```

```bash
$ make build-static-ci; ls -al release/

### Building CI static release/vela-worker binary
total 86312
drwxr-xr-x   3 <user>  staff        96 Apr 15 15:02 .
drwxr-xr-x  27 <user>  staff       864 Apr 15 15:00 ..
-rwxr-xr-x   1 <user>  staff  44191488 Apr 15 15:02 vela-worker
```

2022-04-15 20:08 UTC, cognifloyd commented
Hmm. I'm using a Mac so I build in a docker image. It has never made the binary executable for me.

2022-04-15 20:13 UTC, jbrockopp commented
@cognifloyd that's strange because I work on a Mac as well 😅 

Could you elaborate on what your development workflow looks like?

I ask because traditionally most of us end up using `make restart`, `make up`, or `make down`.

Those commands leverage the `Makefile`, `Dockerfile` and `docker-compose.yml` to create the Vela stack locally.

2022-04-15 20:23 UTC, cognifloyd commented
- attach a console to the build container
- export a custom GITHUB_TAG
- `make build-static` (the same as what the release workflow uses)
- build the Dockerfile with a custom tag
- push the Dockerfile to an internal registry
- update the tag on my helms chart values
- run helm update to update the worker in k8s with the new tag
- stream logs from worker with `stern`

I've had the docker container fail to start many times because the execute bit wasn't set.

I've never used any of the docker-compose bits with Vela.

2022-04-15 20:25 UTC, jbrockopp commented
> attach a console to the build container

Are you saying you build the Go binary inside a Docker container?

2022-04-15 21:35 UTC, cognifloyd commented
Yes. I use the golang:1.17 image with the repo root mounted to `/vela`.

I believe I used https://github.com/go-vela/worker/blob/master/.github/workflows/publish.yml to determine how to build the worker.

2022-04-15 23:46 UTC, cognifloyd commented
Ok. I had some faulty assumptions. I didn't realize go cross compilation worked so well. I tried to duplicate the release build environment, but I guess that wasn't necessary.

So, building it directly on my Mac instead of in the container does make it executable. Perhaps there's something odd about the volume mount that prevented go from adding the executable bit in the container.

In any case, I'm glad to simplify the build steps I've been going through and ditch the build container.

I'll close this now. Thanks for your questions!

2022-04-15 23:46 UTC, closed without merging