tests: Convert executor tests to subtests
go-vela/worker pull request #315
Opened 2022-04-18 15:25 UTC by cognifloyd

I use Goland to run `go test`. At least with Goland, `testing.Run()` improves the output and test selection. And it makes it easier to see which subtest has failed.

As I develop and refactor, I would really like to see this everywhere. This updates all tests under `executor/` as #312 did for `runtime/`.

2022-04-21 16:53 UTC, jbrockopp requested changes
couple quick questions

2022-04-21 16:53 UTC, jbrockopp commented on executor/linux/secret_test.go
>  		// Tests for secrets with image ACLs
Thoughts on removing this comment since we're adding names for the tests now?

2022-04-21 16:53 UTC, jbrockopp commented on executor/linux/secret_test.go
>  		{ // push event checks
Thoughts on removing these comments since we're adding names for the tests now?

2022-04-21 16:53 UTC, jbrockopp commented on executor/linux/secret_test.go
>  		{ // pull_request event checks
Thoughts on removing this comment since we're adding names for the tests now?

2022-04-21 16:53 UTC, jbrockopp commented on executor/linux/secret_test.go
>  		{ // tag event checks
Thoughts on removing this comment since we're adding names for the tests now?

2022-04-21 16:53 UTC, jbrockopp commented on executor/linux/secret_test.go
>  		{ // deployment event checks
Thoughts on removing this comment since we're adding names for the tests now?

2022-04-21 16:53 UTC, jbrockopp commented on executor/linux/secret_test.go
>  		// Tests for secrets with event and image ACLs
Thoughts on removing this comment since we're adding names for the tests now?

2022-04-21 17:02 UTC, cognifloyd reviewed
I left those comments because they visually grouped several related tests. Would you prefer I remove them?

2022-04-21 17:39 UTC, jbrockopp commented on executor/linux/secret_test.go
>  		// Tests for secrets with image ACLs
They certainly don't hurt anything so I suppose we can leave them 👍

2022-04-21 17:40 UTC, jbrockopp approved these changes
LGTM

2022-04-22 14:37 UTC, wass3r approved these changes

2022-04-22 16:03 UTC, merged