feat(internal/skip): add event action handling for skip method
go-vela/worker pull request #326
Opened 2022-04-26 21:21 UTC by ecrupper

Part of the effort for https://github.com/go-vela/community/issues/159

When we determine whether a container should skip at runtime, we check that the events match. With the introduction of `event_action` for scoping, we need to form that string in order to not skip those containers.

2022-04-26 22:18 UTC, cognifloyd approved these changes

2022-04-29 03:31 UTC, wass3r submitted a review, later dismissed

2022-04-29 03:37 UTC, wass3r requested changes
can we throw a test into skip_test to cover action?

2022-04-29 12:28 UTC, wass3r submitted a review, later dismissed
Thanks

2022-04-30 00:32 UTC, cognifloyd approved these changes

2022-04-30 00:33 UTC, merged