enhance(local executor): print to stdout via client field
go-vela/worker pull request #339
Opened 2022-05-12 20:36 UTC by cognifloyd

While working on adding tests for `exec()` in #336, I found that I needed a way to see what the local executor is printing to stdout.

By printing to a stdout field on the local executor, we can allow those tests to capture stdout and make sure the executor is behaving correctly.

2022-05-18 13:26 UTC, jbrockopp requested changes

2022-05-18 14:47 UTC, cognifloyd commented on executor/local/opts.go
> +func WithMockStdout(mock bool) Opt {
`withStreamRequests` is used by tests in the same package (`executor.local`). But, `WithMockStdout` is used in a different package (`executor`) for tests in yet another package (I want to write tests for the `exec()` function in package `main` under `cmd/vela-worker`)

https://github.com/go-vela/worker/blob/0a0f0bd5e11ce5ebf787beccb5dfcfa3dc4bb911/executor/setup.go#L97-L114

So, I'm open to not exporting it, but I didn't see a good way to allow tests in other packages trigger it.

2022-05-18 19:17 UTC, jbrockopp approved these changes
LGTM

2022-06-24 16:52 UTC, wass3r approved these changes

2022-07-14 23:32 UTC, merged