feat/oidc provider
go-vela/worker pull request #581
Opened 2024-05-30 14:37 UTC by plyr4

worker implementation for https://github.com/go-vela/server/pull/1120

2024-05-30 15:17 UTC, KellyMerrick submitted a review, later dismissed
lgtm

2024-06-03 14:29 UTC, ecrupper requested changes
One small thing

2024-06-05 15:56 UTC, wass3rw3rk approved these changes

2024-06-05 16:01 UTC, ecrupper approved these changes

2024-06-05 16:01 UTC, merged